### ISSUE TITLE
New request for space & opacity tokens

### ISSUE THREAD

**Issue by jcusick93** [Supernova-Studio/exporter-documentation#92]
### Description
Can we get a type: space and opacity token? Here is an example of how this might look:

https://polaris.shopify.com/tokens/space

### Related resources
Slack discussion: 

User docs ticket: 

Wireframe
- **TODO**

Design
- **TODO**

### Acceptance criteria
1. **TODO**

**Comment by jcusick93** [comment]
@JiriTrecak

**Comment by honzatmn** [comment]
Hey @jcusick93, thank you for reaching out. This would be a feature request for the product since we're not yet supporting space or opacity token types in our token management. I'll track it in our feedback tool. However, I think I can say that introducing several more token types are on our roadmap 👀
